name: "Get Logs"

on:
  workflow_dispatch:

jobs:
  get-logs:
    runs-on: ubuntu-latest
    steps:
      - name: Get logs from docker
        uses: appleboy/ssh-action@master
        with:
          host: capstone-project.de
          #Set App Name (replace "example" with "alpha"-"tango")
          username: cgn-java-23-2-alexander
          password: ${{ secrets.SSH_PASSWORD }}
          #Set App Name (replace "example" with "alpha"-"tango")
          script: |
            sudo docker logs cgn-java-23-2-alexander
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v3
        with:
          #Set App Name (replace "example" with "alpha"-"tango")
          url: http://cgn-java-23-2-alexander.capstone-project.de
          max-attempts: 3
          retry-delay: 5s
          retry-all: true
